var questions = [
["la falda","spódnica"],
["el bolso","torebka"],
["el abrigo","żakiet"],
["la camisa","koszula"],
["el pantalón","spodnie"],
["la camiseta","koszulka"],
["el vestido","suknia"],
["el traje de caballero","garnitur"],
["las sandalias","sandały"],
["los zapatos","buty"],
["las gafas de sol","okulary przeciwsłoneczne"],
["los guantes","rękawiczki"],
["el biquini","bikini"],
["... cuesta ...","... kosztuje ..."],
["... cuestan ...","... kosztują ..."],
["de flores","w kwiaty"],
["de rayas","w paski"],
["de lunares","w kropki"],
["liso","gładki"],
["llevar","nosić ubranie"],
["empezar","rozpoczynać się"],
["la primavera","wiosna"],
["el verano","lato"],
["el otoño","jesień"],
["el invierno","zima"],
["el viento","wiatr"],
["la nieve","śnieg"],
["el sol","słońce"],
["la lluvia","deszcz"],
["la tormenta","burza"],
["nubes y claros","przejaśnienie"],
["nublado","pochmurno"],
["la niebla","mgła"],
["calor","ciepło"],
["frío","zimno, zimny"],
["Llueve.","Pada deszcz."],
["Nieva.","Pada śnieg."]
];
